//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TryOut
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TryOut()
        {
            this.Stage = new HashSet<Stage>();
        }
    
        public int TryOutId { get; set; }
        public string TryOutName { get; set; }
        public Nullable<System.DateTime> TryOutDate { get; set; }
        public Nullable<int> TryOutWinnerId { get; set; }
        public Nullable<System.TimeSpan> TryOutDurationTime { get; set; }
        public int TryOutTypeId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stage> Stage { get; set; }
        public virtual TryOutType TryOutType { get; set; }
    }
}
