<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Administration extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Administration_model');
    } 

    /*
     * Listing of administration
     */
    function index()
    {
        $data['administration'] = $this->Administration_model->get_all_administration();
        
        $data['_view'] = 'administration/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new administration
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
            );
            
            $administration_id = $this->Administration_model->add_administration($params);
            redirect('administration/index');
        }
        else
        {            
            $data['_view'] = 'administration/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a administration
     */
    function edit($FederationID)
    {   
        // check if the administration exists before trying to edit it
        $data['administration'] = $this->Administration_model->get_administration($FederationID);
        
        if(isset($data['administration']['FederationID']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
                );

                $this->Administration_model->update_administration($FederationID,$params);            
                redirect('administration/index');
            }
            else
            {
                $data['_view'] = 'administration/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The administration you are trying to edit does not exist.');
    } 

    /*
     * Deleting administration
     */
    function remove($FederationID)
    {
        $administration = $this->Administration_model->get_administration($FederationID);

        // check if the administration exists before trying to delete it
        if(isset($administration['FederationID']))
        {
            $this->Administration_model->delete_administration($FederationID);
            redirect('administration/index');
        }
        else
            show_error('The administration you are trying to delete does not exist.');
    }
    
}
