<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Competitor extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Competitor_model');
    } 

    /*
     * Listing of competitor
     */
    function index()
    {
        $data['competitor'] = $this->Competitor_model->get_all_competitor();
        
        $data['_view'] = 'competitor/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new competitor
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'NumberId' => $this->input->post('NumberId'),
            );
            
            $competitor_id = $this->Competitor_model->add_competitor($params);
            redirect('competitor/index');
        }
        else
        {            
            $data['_view'] = 'competitor/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a competitor
     */
    function edit($CompetitorId)
    {   
        // check if the competitor exists before trying to edit it
        $data['competitor'] = $this->Competitor_model->get_competitor($CompetitorId);
        
        if(isset($data['competitor']['CompetitorId']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'NumberId' => $this->input->post('NumberId'),
                );

                $this->Competitor_model->update_competitor($CompetitorId,$params);            
                redirect('competitor/index');
            }
            else
            {
                $data['_view'] = 'competitor/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The competitor you are trying to edit does not exist.');
    } 

    /*
     * Deleting competitor
     */
    function remove($CompetitorId)
    {
        $competitor = $this->Competitor_model->get_competitor($CompetitorId);

        // check if the competitor exists before trying to delete it
        if(isset($competitor['CompetitorId']))
        {
            $this->Competitor_model->delete_competitor($CompetitorId);
            redirect('competitor/index');
        }
        else
            show_error('The competitor you are trying to delete does not exist.');
    }
    
}
