<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Federation extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Federation_model');
    } 

    /*
     * Listing of federation
     */
    function index()
    {
        $data['federation'] = $this->Federation_model->get_all_federation();
        
        $data['_view'] = 'federation/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new federation
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'FederationName' => $this->input->post('FederationName'),
				'FederatedNumber' => $this->input->post('FederatedNumber'),
            );
            
            $federation_id = $this->Federation_model->add_federation($params);
            redirect('federation/index');
        }
        else
        {            
            $data['_view'] = 'federation/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a federation
     */
    function edit($FederationID)
    {   
        // check if the federation exists before trying to edit it
        $data['federation'] = $this->Federation_model->get_federation($FederationID);
        
        if(isset($data['federation']['FederationID']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'FederationName' => $this->input->post('FederationName'),
					'FederatedNumber' => $this->input->post('FederatedNumber'),
                );

                $this->Federation_model->update_federation($FederationID,$params);            
                redirect('federation/index');
            }
            else
            {
                $data['_view'] = 'federation/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The federation you are trying to edit does not exist.');
    } 

    /*
     * Deleting federation
     */
    function remove($FederationID)
    {
        $federation = $this->Federation_model->get_federation($FederationID);

        // check if the federation exists before trying to delete it
        if(isset($federation['FederationID']))
        {
            $this->Federation_model->delete_federation($FederationID);
            redirect('federation/index');
        }
        else
            show_error('The federation you are trying to delete does not exist.');
    }
    
}
