<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Route extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Route_model');
    } 

    /*
     * Listing of route
     */
    function index()
    {
        $data['route'] = $this->Route_model->get_all_route();
        
        $data['_view'] = 'route/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new route
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'SeasonId' => $this->input->post('SeasonId'),
				'StageId' => $this->input->post('StageId'),
            );
            
            $route_id = $this->Route_model->add_route($params);
            redirect('route/index');
        }
        else
        {            
            $data['_view'] = 'route/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a route
     */
    function edit($RouteId)
    {   
        // check if the route exists before trying to edit it
        $data['route'] = $this->Route_model->get_route($RouteId);
        
        if(isset($data['route']['RouteId']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'SeasonId' => $this->input->post('SeasonId'),
					'StageId' => $this->input->post('StageId'),
                );

                $this->Route_model->update_route($RouteId,$params);            
                redirect('route/index');
            }
            else
            {
                $data['_view'] = 'route/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The route you are trying to edit does not exist.');
    } 

    /*
     * Deleting route
     */
    function remove($RouteId)
    {
        $route = $this->Route_model->get_route($RouteId);

        // check if the route exists before trying to delete it
        if(isset($route['RouteId']))
        {
            $this->Route_model->delete_route($RouteId);
            redirect('route/index');
        }
        else
            show_error('The route you are trying to delete does not exist.');
    }
    
}
