<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Skier extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Skier_model');
    } 

    /*
     * Listing of skier
     */
    function index()
    {
        $data['skier'] = $this->Skier_model->get_all_skier();
        
        $data['_view'] = 'skier/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new skier
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'SkierName' => $this->input->post('SkierName'),
				'Birthdate' => $this->input->post('Birthdate'),
				'FederationID' => $this->input->post('FederationID'),
            );
            
            $skier_id = $this->Skier_model->add_skier($params);
            redirect('skier/index');
        }
        else
        {            
            $data['_view'] = 'skier/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a skier
     */
    function edit($NumberId)
    {   
        // check if the skier exists before trying to edit it
        $data['skier'] = $this->Skier_model->get_skier($NumberId);
        
        if(isset($data['skier']['NumberId']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'SkierName' => $this->input->post('SkierName'),
					'Birthdate' => $this->input->post('Birthdate'),
					'FederationID' => $this->input->post('FederationID'),
                );

                $this->Skier_model->update_skier($NumberId,$params);            
                redirect('skier/index');
            }
            else
            {
                $data['_view'] = 'skier/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The skier you are trying to edit does not exist.');
    } 

    /*
     * Deleting skier
     */
    function remove($NumberId)
    {
        $skier = $this->Skier_model->get_skier($NumberId);

        // check if the skier exists before trying to delete it
        if(isset($skier['NumberId']))
        {
            $this->Skier_model->delete_skier($NumberId);
            redirect('skier/index');
        }
        else
            show_error('The skier you are trying to delete does not exist.');
    }
    
}
