<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Teammember extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Teammember_model');
    } 

    /*
     * Listing of teammember
     */
    function index()
    {
        $data['teammember'] = $this->Teammember_model->get_all_teammember();
        
        $data['_view'] = 'teammember/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new teammember
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'TeamId' => $this->input->post('TeamId'),
				'NumberId' => $this->input->post('NumberId'),
            );
            
            $teammember_id = $this->Teammember_model->add_teammember($params);
            redirect('teammember/index');
        }
        else
        {            
            $data['_view'] = 'teammember/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a teammember
     */
    function edit($TeamMemberId)
    {   
        // check if the teammember exists before trying to edit it
        $data['teammember'] = $this->Teammember_model->get_teammember($TeamMemberId);
        
        if(isset($data['teammember']['TeamMemberId']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'TeamId' => $this->input->post('TeamId'),
					'NumberId' => $this->input->post('NumberId'),
                );

                $this->Teammember_model->update_teammember($TeamMemberId,$params);            
                redirect('teammember/index');
            }
            else
            {
                $data['_view'] = 'teammember/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The teammember you are trying to edit does not exist.');
    } 

    /*
     * Deleting teammember
     */
    function remove($TeamMemberId)
    {
        $teammember = $this->Teammember_model->get_teammember($TeamMemberId);

        // check if the teammember exists before trying to delete it
        if(isset($teammember['TeamMemberId']))
        {
            $this->Teammember_model->delete_teammember($TeamMemberId);
            redirect('teammember/index');
        }
        else
            show_error('The teammember you are trying to delete does not exist.');
    }
    
}
