<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Team extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Team_model');
    } 

    /*
     * Listing of team
     */
    function index()
    {
        $data['team'] = $this->Team_model->get_all_team();
        
        $data['_view'] = 'team/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new team
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'TeamName' => $this->input->post('TeamName'),
				'CoachName' => $this->input->post('CoachName'),
				'SkiersNumber' => $this->input->post('SkiersNumber'),
            );
            
            $team_id = $this->Team_model->add_team($params);
            redirect('team/index');
        }
        else
        {            
            $data['_view'] = 'team/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a team
     */
    function edit($TeamId)
    {   
        // check if the team exists before trying to edit it
        $data['team'] = $this->Team_model->get_team($TeamId);
        
        if(isset($data['team']['TeamId']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'TeamName' => $this->input->post('TeamName'),
					'CoachName' => $this->input->post('CoachName'),
					'SkiersNumber' => $this->input->post('SkiersNumber'),
                );

                $this->Team_model->update_team($TeamId,$params);            
                redirect('team/index');
            }
            else
            {
                $data['_view'] = 'team/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The team you are trying to edit does not exist.');
    } 

    /*
     * Deleting team
     */
    function remove($TeamId)
    {
        $team = $this->Team_model->get_team($TeamId);

        // check if the team exists before trying to delete it
        if(isset($team['TeamId']))
        {
            $this->Team_model->delete_team($TeamId);
            redirect('team/index');
        }
        else
            show_error('The team you are trying to delete does not exist.');
    }
    
}
