<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tm_audit extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tm_audit_model');
    } 

    /*
     * Listing of tm_audit
     */
    function index()
    {
        $data['tm_audit'] = $this->Tm_audit_model->get_all_tm_audit();
        
        $data['_view'] = 'tm_audit/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new tm_audit
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'TableId' => $this->input->post('TableId'),
				'ActionId' => $this->input->post('ActionId'),
				'AuditDate' => $this->input->post('AuditDate'),
				'UserId' => $this->input->post('UserId'),
            );
            
            $tm_audit_id = $this->Tm_audit_model->add_tm_audit($params);
            redirect('tm_audit/index');
        }
        else
        {            
            $data['_view'] = 'tm_audit/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a tm_audit
     */
    function edit($ModifyId)
    {   
        // check if the tm_audit exists before trying to edit it
        $data['tm_audit'] = $this->Tm_audit_model->get_tm_audit($ModifyId);
        
        if(isset($data['tm_audit']['ModifyId']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'TableId' => $this->input->post('TableId'),
					'ActionId' => $this->input->post('ActionId'),
					'AuditDate' => $this->input->post('AuditDate'),
					'UserId' => $this->input->post('UserId'),
                );

                $this->Tm_audit_model->update_tm_audit($ModifyId,$params);            
                redirect('tm_audit/index');
            }
            else
            {
                $data['_view'] = 'tm_audit/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The tm_audit you are trying to edit does not exist.');
    } 

    /*
     * Deleting tm_audit
     */
    function remove($ModifyId)
    {
        $tm_audit = $this->Tm_audit_model->get_tm_audit($ModifyId);

        // check if the tm_audit exists before trying to delete it
        if(isset($tm_audit['ModifyId']))
        {
            $this->Tm_audit_model->delete_tm_audit($ModifyId);
            redirect('tm_audit/index');
        }
        else
            show_error('The tm_audit you are trying to delete does not exist.');
    }
    
}
