<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Track_route extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Track_route_model');
    } 

    /*
     * Listing of track_route
     */
    function index()
    {
        $data['track_route'] = $this->Track_route_model->get_all_track_route();
        
        $data['_view'] = 'track_route/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new track_route
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'SequentialNumber' => $this->input->post('SequentialNumber'),
            );
            
            $track_route_id = $this->Track_route_model->add_track_route($params);
            redirect('track_route/index');
        }
        else
        {            
            $data['_view'] = 'track_route/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a track_route
     */
    function edit($RouteId)
    {   
        // check if the track_route exists before trying to edit it
        $data['track_route'] = $this->Track_route_model->get_track_route($RouteId);
        
        if(isset($data['track_route']['RouteId']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'SequentialNumber' => $this->input->post('SequentialNumber'),
                );

                $this->Track_route_model->update_track_route($RouteId,$params);            
                redirect('track_route/index');
            }
            else
            {
                $data['_view'] = 'track_route/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The track_route you are trying to edit does not exist.');
    } 

    /*
     * Deleting track_route
     */
    function remove($RouteId)
    {
        $track_route = $this->Track_route_model->get_track_route($RouteId);

        // check if the track_route exists before trying to delete it
        if(isset($track_route['RouteId']))
        {
            $this->Track_route_model->delete_track_route($RouteId);
            redirect('track_route/index');
        }
        else
            show_error('The track_route you are trying to delete does not exist.');
    }
    
}
