<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tryouttype extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tryouttype_model');
    } 

    /*
     * Listing of tryouttype
     */
    function index()
    {
        $data['tryouttype'] = $this->Tryouttype_model->get_all_tryouttype();
        
        $data['_view'] = 'tryouttype/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new tryouttype
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'TryOutTypeDescription' => $this->input->post('TryOutTypeDescription'),
            );
            
            $tryouttype_id = $this->Tryouttype_model->add_tryouttype($params);
            redirect('tryouttype/index');
        }
        else
        {            
            $data['_view'] = 'tryouttype/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a tryouttype
     */
    function edit($TryOutTypeId)
    {   
        // check if the tryouttype exists before trying to edit it
        $data['tryouttype'] = $this->Tryouttype_model->get_tryouttype($TryOutTypeId);
        
        if(isset($data['tryouttype']['TryOutTypeId']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'TryOutTypeDescription' => $this->input->post('TryOutTypeDescription'),
                );

                $this->Tryouttype_model->update_tryouttype($TryOutTypeId,$params);            
                redirect('tryouttype/index');
            }
            else
            {
                $data['_view'] = 'tryouttype/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The tryouttype you are trying to edit does not exist.');
    } 

    /*
     * Deleting tryouttype
     */
    function remove($TryOutTypeId)
    {
        $tryouttype = $this->Tryouttype_model->get_tryouttype($TryOutTypeId);

        // check if the tryouttype exists before trying to delete it
        if(isset($tryouttype['TryOutTypeId']))
        {
            $this->Tryouttype_model->delete_tryouttype($TryOutTypeId);
            redirect('tryouttype/index');
        }
        else
            show_error('The tryouttype you are trying to delete does not exist.');
    }
    
}
