//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tm_Audit
    {
        public string TableId { get; set; }
        public string ActionId { get; set; }
        public Nullable<System.DateTime> AuditDate { get; set; }
        public string UserId { get; set; }
        public int ModifyId { get; set; }
    }
}
