//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Track_Route
    {
        public int RouteId { get; set; }
        public int CoTrack { get; set; }
        public Nullable<int> SequentialNumber { get; set; }
    
        public virtual Route Route { get; set; }
    }
}
