<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Administration_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get administration by FederationID
     */
    function get_administration($FederationID)
    {
        return $this->db->get_where('Administration',array('FederationID'=>$FederationID))->row_array();
    }
        
    /*
     * Get all administration
     */
    function get_all_administration()
    {
        $this->db->order_by('FederationID', 'desc');
        return $this->db->get('Administration')->result_array();
    }
        
    /*
     * function to add new administration
     */
    function add_administration($params)
    {
        $this->db->insert('Administration',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update administration
     */
    function update_administration($FederationID,$params)
    {
        $this->db->where('FederationID',$FederationID);
        return $this->db->update('Administration',$params);
    }
    
    /*
     * function to delete administration
     */
    function delete_administration($FederationID)
    {
        return $this->db->delete('Administration',array('FederationID'=>$FederationID));
    }
}
