<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Competitor_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get competitor by CompetitorId
     */
    function get_competitor($CompetitorId)
    {
        return $this->db->get_where('Competitor',array('CompetitorId'=>$CompetitorId))->row_array();
    }
        
    /*
     * Get all competitor
     */
    function get_all_competitor()
    {
        $this->db->order_by('CompetitorId', 'desc');
        return $this->db->get('Competitor')->result_array();
    }
        
    /*
     * function to add new competitor
     */
    function add_competitor($params)
    {
        $this->db->insert('Competitor',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update competitor
     */
    function update_competitor($CompetitorId,$params)
    {
        $this->db->where('CompetitorId',$CompetitorId);
        return $this->db->update('Competitor',$params);
    }
    
    /*
     * function to delete competitor
     */
    function delete_competitor($CompetitorId)
    {
        return $this->db->delete('Competitor',array('CompetitorId'=>$CompetitorId));
    }
}
