<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Federation_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get federation by FederationID
     */
    function get_federation($FederationID)
    {
        return $this->db->get_where('Federation',array('FederationID'=>$FederationID))->row_array();
    }
        
    /*
     * Get all federation
     */
    function get_all_federation()
    {
        $this->db->order_by('FederationID', 'desc');
        return $this->db->get('Federation')->result_array();
    }
        
    /*
     * function to add new federation
     */
    function add_federation($params)
    {
        $this->db->insert('Federation',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update federation
     */
    function update_federation($FederationID,$params)
    {
        $this->db->where('FederationID',$FederationID);
        return $this->db->update('Federation',$params);
    }
    
    /*
     * function to delete federation
     */
    function delete_federation($FederationID)
    {
        return $this->db->delete('Federation',array('FederationID'=>$FederationID));
    }
}
