<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Intervention_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get intervention by CompetitorId
     */
    function get_intervention($CompetitorId)
    {
        return $this->db->get_where('Intervention',array('CompetitorId'=>$CompetitorId))->row_array();
    }
        
    /*
     * Get all intervention
     */
    function get_all_intervention()
    {
        $this->db->order_by('CompetitorId', 'desc');
        return $this->db->get('Intervention')->result_array();
    }
        
    /*
     * function to add new intervention
     */
    function add_intervention($params)
    {
        $this->db->insert('Intervention',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update intervention
     */
    function update_intervention($CompetitorId,$params)
    {
        $this->db->where('CompetitorId',$CompetitorId);
        return $this->db->update('Intervention',$params);
    }
    
    /*
     * function to delete intervention
     */
    function delete_intervention($CompetitorId)
    {
        return $this->db->delete('Intervention',array('CompetitorId'=>$CompetitorId));
    }
}
