<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Route_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get route by RouteId
     */
    function get_route($RouteId)
    {
        return $this->db->get_where('Route',array('RouteId'=>$RouteId))->row_array();
    }
        
    /*
     * Get all route
     */
    function get_all_route()
    {
        $this->db->order_by('RouteId', 'desc');
        return $this->db->get('Route')->result_array();
    }
        
    /*
     * function to add new route
     */
    function add_route($params)
    {
        $this->db->insert('Route',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update route
     */
    function update_route($RouteId,$params)
    {
        $this->db->where('RouteId',$RouteId);
        return $this->db->update('Route',$params);
    }
    
    /*
     * function to delete route
     */
    function delete_route($RouteId)
    {
        return $this->db->delete('Route',array('RouteId'=>$RouteId));
    }
}
