<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Skier_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get skier by NumberId
     */
    function get_skier($NumberId)
    {
        return $this->db->get_where('Skier',array('NumberId'=>$NumberId))->row_array();
    }
        
    /*
     * Get all skier
     */
    function get_all_skier()
    {
        $this->db->order_by('NumberId', 'desc');
        return $this->db->get('Skier')->result_array();
    }
        
    /*
     * function to add new skier
     */
    function add_skier($params)
    {
        $this->db->insert('Skier',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update skier
     */
    function update_skier($NumberId,$params)
    {
        $this->db->where('NumberId',$NumberId);
        return $this->db->update('Skier',$params);
    }
    
    /*
     * function to delete skier
     */
    function delete_skier($NumberId)
    {
        return $this->db->delete('Skier',array('NumberId'=>$NumberId));
    }
}
