<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Teammember_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get teammember by TeamMemberId
     */
    function get_teammember($TeamMemberId)
    {
        return $this->db->get_where('TeamMember',array('TeamMemberId'=>$TeamMemberId))->row_array();
    }
        
    /*
     * Get all teammember
     */
    function get_all_teammember()
    {
        $this->db->order_by('TeamMemberId', 'desc');
        return $this->db->get('TeamMember')->result_array();
    }
        
    /*
     * function to add new teammember
     */
    function add_teammember($params)
    {
        $this->db->insert('TeamMember',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update teammember
     */
    function update_teammember($TeamMemberId,$params)
    {
        $this->db->where('TeamMemberId',$TeamMemberId);
        return $this->db->update('TeamMember',$params);
    }
    
    /*
     * function to delete teammember
     */
    function delete_teammember($TeamMemberId)
    {
        return $this->db->delete('TeamMember',array('TeamMemberId'=>$TeamMemberId));
    }
}
