<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tm_audit_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tm_audit by 
     */
    function get_tm_audit($)
    {
        return $this->db->get_where('Tm_Audit',array(''=>$))->row_array();
    }
        
    /*
     * Get all tm_audit
     */
    function get_all_tm_audit()
    {
        $this->db->order_by('', 'desc');
        return $this->db->get('Tm_Audit')->result_array();
    }
        
    /*
     * function to add new tm_audit
     */
    function add_tm_audit($params)
    {
        $this->db->insert('Tm_Audit',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tm_audit
     */
    function update_tm_audit($,$params)
    {
        $this->db->where('',$);
        return $this->db->update('Tm_Audit',$params);
    }
    
    /*
     * function to delete tm_audit
     */
    function delete_tm_audit($)
    {
        return $this->db->delete('Tm_Audit',array(''=>$));
    }
}
