<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Track_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get track by TrackId
     */
    function get_track($TrackId)
    {
        return $this->db->get_where('Track',array('TrackId'=>$TrackId))->row_array();
    }
        
    /*
     * Get all track
     */
    function get_all_track()
    {
        $this->db->order_by('TrackId', 'desc');
        return $this->db->get('Track')->result_array();
    }
        
    /*
     * function to add new track
     */
    function add_track($params)
    {
        $this->db->insert('Track',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update track
     */
    function update_track($TrackId,$params)
    {
        $this->db->where('TrackId',$TrackId);
        return $this->db->update('Track',$params);
    }
    
    /*
     * function to delete track
     */
    function delete_track($TrackId)
    {
        return $this->db->delete('Track',array('TrackId'=>$TrackId));
    }
}
