<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Track_route_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get track_route by RouteId
     */
    function get_track_route($RouteId)
    {
        return $this->db->get_where('Track_Route',array('RouteId'=>$RouteId))->row_array();
    }
        
    /*
     * Get all track_route
     */
    function get_all_track_route()
    {
        $this->db->order_by('RouteId', 'desc');
        return $this->db->get('Track_Route')->result_array();
    }
        
    /*
     * function to add new track_route
     */
    function add_track_route($params)
    {
        $this->db->insert('Track_Route',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update track_route
     */
    function update_track_route($RouteId,$params)
    {
        $this->db->where('RouteId',$RouteId);
        return $this->db->update('Track_Route',$params);
    }
    
    /*
     * function to delete track_route
     */
    function delete_track_route($RouteId)
    {
        return $this->db->delete('Track_Route',array('RouteId'=>$RouteId));
    }
}
