<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tryouttype_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tryouttype by TryOutTypeId
     */
    function get_tryouttype($TryOutTypeId)
    {
        return $this->db->get_where('TryOutType',array('TryOutTypeId'=>$TryOutTypeId))->row_array();
    }
        
    /*
     * Get all tryouttype
     */
    function get_all_tryouttype()
    {
        $this->db->order_by('TryOutTypeId', 'desc');
        return $this->db->get('TryOutType')->result_array();
    }
        
    /*
     * function to add new tryouttype
     */
    function add_tryouttype($params)
    {
        $this->db->insert('TryOutType',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tryouttype
     */
    function update_tryouttype($TryOutTypeId,$params)
    {
        $this->db->where('TryOutTypeId',$TryOutTypeId);
        return $this->db->update('TryOutType',$params);
    }
    
    /*
     * function to delete tryouttype
     */
    function delete_tryouttype($TryOutTypeId)
    {
        return $this->db->delete('TryOutType',array('TryOutTypeId'=>$TryOutTypeId));
    }
}
